using UnityEngine;
using System.Collections.Generic;
using UnityEngine.Tilemaps;


public class LevelGenerator : MonoBehaviour
{
    [SerializeField] private int hubExitHeight = 1;
    [SerializeField] private int roomsPerLevel = 3;

    [SerializeField] private RoomData firstRoom;
    [SerializeField] private List<RoomData> lastRooms = new List<RoomData>();
    [SerializeField] private List<RoomData> rooms = new List<RoomData>();
    private List<RoomData> selectedRooms = new List<RoomData>();
    [SerializeField] private bool debugPlacement = true;

    void Start()
    {
        GenerateLevel();
    }
    void GenerateLevel()
{
    selectedRooms.Clear();
    selectedRooms.Add(firstRoom);
    int currentHeight = firstRoom.exitHeight;

    for (int i = 0; i < roomsPerLevel-1; i++)
    {
        List<RoomData> matchingRooms = rooms.FindAll(room => room.entryHeight == currentHeight);
        if (matchingRooms.Count > 0)
        {
            RoomData pickedRoom = matchingRooms[Random.Range(0, matchingRooms.Count)];
            selectedRooms.Add(pickedRoom);
            matchingRooms.Remove(pickedRoom);
            currentHeight = pickedRoom.exitHeight;
        }
        else
        {
            Debug.LogError($"No room found with entry height {currentHeight}!");
            break;
        }
    }   
    
    List<RoomData> matchingLastRooms = lastRooms.FindAll(room => room.entryHeight == currentHeight);
    if (matchingLastRooms.Count > 0)
    {
        selectedRooms.Add(matchingLastRooms[0]);
    }
    else
    {
        Debug.LogError($"No last room found with entry height {currentHeight}!");
    }
    
    Vector3 nextPosition = Vector3.zero;
    float baselineWorldY = 0f;
    
    List<GameObject> instantiatedRooms = new List<GameObject>();

    // Code below was generated by AI and is responsible for placing rooms in the level
    for (int i = 0; i < selectedRooms.Count; i++)
    {
        RoomData room = selectedRooms[i];
        GameObject roomGO = Instantiate(room.gameObject, transform);

        Tilemap tilemap = roomGO.GetComponentInChildren<Tilemap>();
        tilemap.CompressBounds();
        BoundsInt bounds = tilemap.cellBounds;

        int entryIndex = bounds.yMin + room.entryHeight;
        int exitIndex = bounds.yMin + room.exitHeight;

        Vector3 tilemapLocalOffset = tilemap.transform.localPosition;

        Vector3 leftBottomLocal = tilemap.CellToLocal(new Vector3Int(bounds.xMin, bounds.yMin, 0));
        Vector3 entryLocal = tilemap.CellToLocal(new Vector3Int(bounds.xMin, entryIndex, 0));
        Vector3 exitLocal = tilemap.CellToLocal(new Vector3Int(bounds.xMin, exitIndex, 0));

        Vector3 cellSize = tilemap.layoutGrid.cellSize;


        float placeX = nextPosition.x - (tilemapLocalOffset.x + leftBottomLocal.x);
        float placeY = baselineWorldY - (tilemapLocalOffset.y + entryLocal.y);

        if (debugPlacement)
        {
            Debug.Log($"[LevelGenerator] Room '{room.name}' idx={i}");
            Debug.Log($"  tilemapLocalOffset={tilemapLocalOffset}");
            Debug.Log($"  entryLocal={entryLocal}, exitLocal={exitLocal}");
            Debug.Log($"  baselineWorldY={baselineWorldY}, placeY={placeY}");
        }

        roomGO.transform.localPosition = new Vector3(placeX, placeY, 0f);

        baselineWorldY = placeY + tilemapLocalOffset.y + exitLocal.y;

        nextPosition.x += bounds.size.x * cellSize.x;
        instantiatedRooms.Add(roomGO);
    }
}

 
}